# Generated by Django 4.0.3 on 2023-06-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
